import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";

// ... other imports


const fontspring = localfont({
  src: [
    { path: "./fonts/proximanova_regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/proximanova_bold.otf", weight: "700", style: "normal" },
  ],
  variable: "--font-fontspring",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sam Anisulowo Foundation",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontspring.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
