import type { Metadata } from "next";
import "./globals.css";
import { fontspring } from "../lib/fonts";

// ... other imports

export const metadata: Metadata = {
  title: "Sam Anisulowo Foundation",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontspring.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
